# Generated by Django 4.1.7 on 2023-03-21 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gps",
            name="time",
        ),
        migrations.AddField(
            model_name="gps",
            name="data",
            field=models.CharField(default="", max_length=200),
        ),
    ]
