# Generated by Django 4.1.7 on 2023-03-25 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gps", "0003_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="gps",
        ),
        migrations.AlterModelOptions(
            name="location",
            options={"verbose_name": "定位", "verbose_name_plural": "定位"},
        ),
    ]
